dist: bionic
language: generic
# Keep this list in sync with that in config
matrix:
  include:
  - os: linux
  - os: linux
    arch: arm64
services:
- docker
script:
- bash build.sh
deploy:
- provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(av-.*)$
env:
  global:
  - DOCKER_USER=andreabolognani
  - secure: LEoTgROAXzxHos3xEtvC/nu86Zh3rvtfRRYXze22XZq6+G6QDAxbKFhyiGCkfV9q/l5cipzT2M1XTu4vUcOx6jw8i1SUGMAAJrwOFhyOq344QCVEBHUzRBw6HIRb6KTz1ERbx9vXWRXX/cVY5AnhckldJnsLfrQy/scaaPDs1wayrijo9LhrOrWNvyfO+2Mkxqj+6Hc6BDJ0KNCvm19zLzqq2BFNRdu1nb4sGfMctOC444M8zWrmvyaWeWtExOqJjNkWALvjcIauG64IoG7yRYPa/ZAFbL+SOiI4FqErSreN+Qb9Ob563ezY2RDlqqHc/3AeRtCewxoKruRHFuOdHq/5tWYZre//Wh33iUfbuHz7fd8ql4PwLtx6sMBh1mr3ECxYBKm42HpbfQNF3DTZiFylZirZMWKHUzJ2PI4wDc5eeunZuBb7Ou2wz8rGu1A+gqY0ibDLJFA1PWxzOg+D7Q23SxSX2Fu/vL4H5FWetpMphSle2qqtOgYktp2/hHplTexxhkJufFn+06/NCx3WOL9Xb3ymGqCBmeCEYY4oaowUy1C99dz/UZYeJKWH3zqeyciLcI6aDYCSJQ1gihA3EvjVh+1ldXZQ35prdvM2FJWk0CM8zDsuhFow6RrVPpDRqTg5+PHVsacM1fIQT/XoeF2j3RRpi3IRWP5G+AE4irg=
